server:
  port: 9528
spring:
  application:
    name: cloudalibaba-sentinel-gateway  #sentinel+gateway整合实现服务限流
  cloud:
    nacos:
      discover:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pay_routh1 #路由id(pay_routh1),类似mysql中的主键id，没有固定规则但要求唯一
          uri: http://localhost:9001 #匹配后提供服务的路由地址
          predicates: #断言，路径相匹配的进行路由
            - Path=/pay/**