server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    gateway:
      routes:
        - id: pay_routh1 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/** #断言，路径相匹配的进行路由
            - My=gold # 自定义的网关配置
#            - name: My
#              args:
#                userType: gold

        - id: pay_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**

        - id: pay_routh3 #pay_routh3测试GatewayFilter过滤器
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
          filters:
            - AddRequestHeader=X-Request-power1,powerVal1
            #- AddRequestHeader=X-Request-power2,powerVal2
            #- RemoveRequestHeader=sec-fetch-site #删除请求头